# Generated by Django 4.2.16 on 2026-05-24 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sessions_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionPosee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auteur",
                    models.CharField(
                        choices=[("ia", "IA"), ("prof", "Professeur")],
                        default="ia",
                        max_length=10,
                    ),
                ),
                ("question", models.TextField()),
                ("reponse_etudiant", models.TextField(blank=True)),
                ("evaluation_ia", models.TextField(blank=True)),
                ("note_reponse", models.FloatField(blank=True, null=True)),
                ("date_posee", models.DateTimeField(auto_now_add=True)),
                (
                    "passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_posees",
                        to="sessions_app.passageetudiant",
                    ),
                ),
            ],
            options={
                "ordering": ["date_posee"],
            },
        ),
        migrations.CreateModel(
            name="NoteIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_ia",
                    models.FloatField(help_text="Note brute donnée par Claude (0-20)"),
                ),
                (
                    "note_finale",
                    models.FloatField(
                        help_text="Note finale (initialement = note_ia, modifiable par le prof)"
                    ),
                ),
                ("commentaire_ia", models.TextField(blank=True)),
                ("commentaire_prof", models.TextField(blank=True)),
                ("modifiee_par_prof", models.BooleanField(default=False)),
                ("date_notation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "critere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_attribuees",
                        to="sessions_app.criterenotation",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_obtenues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="sessions_app.passageetudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note IA",
                "verbose_name_plural": "Notes IA",
                "ordering": ["critere__ordre"],
                "unique_together": {("passage", "etudiant", "critere")},
            },
        ),
    ]
