# Generated by Django 4.2.16 on 2026-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_profil",
            field=models.ImageField(
                blank=True,
                help_text="Photo nette de face — utilisée pour la reconnaissance faciale pendant la soutenance.",
                null=True,
                upload_to="photos_profil/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
