# Generated by Django 4.2.16 on 2026-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_photo_profil"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("H", "Homme"), ("F", "Femme")],
                default="",
                help_text="Utilisé pour choisir l'avatar du professeur dans la salle.",
                max_length=1,
                verbose_name="Sexe",
            ),
        ),
    ]
