# Generated by Django 4.2.16 on 2026-05-24 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "Anglais"),
                            ("ar", "Arabe / Darija"),
                            ("es", "Espagnol"),
                            ("de", "Allemand"),
                        ],
                        default="fr",
                        max_length=4,
                    ),
                ),
                (
                    "duree_presentation",
                    models.PositiveIntegerField(
                        default=15, help_text="Durée présentation en minutes"
                    ),
                ),
                (
                    "duree_questions",
                    models.PositiveIntegerField(
                        default=5, help_text="Durée session questions en minutes"
                    ),
                ),
                ("nb_questions_max", models.PositiveIntegerField(default=3)),
                ("rapport_obligatoire", models.BooleanField(default=False)),
                ("coefficient_rapport", models.FloatField(default=1.0)),
                (
                    "personnalite_ia",
                    models.CharField(
                        choices=[
                            ("neutre", "Neutre — évaluation objective"),
                            ("severe", "Sévère — exigeant"),
                            ("empathique", "Empathique — bienveillant"),
                            ("gentil", "Gentil — encourageant"),
                        ],
                        default="neutre",
                        max_length=20,
                    ),
                ),
                (
                    "consignes_ia",
                    models.TextField(
                        blank=True,
                        help_text="Instructions libres pour l'IA (contexte, focus particulier...)",
                    ),
                ),
                (
                    "mode_notation_groupe",
                    models.CharField(
                        choices=[
                            ("identique", "Note identique pour tout le groupe"),
                            ("individuelle", "Note individuelle pour chaque membre"),
                            ("mixte", "Mixte (groupe + individuelle pondérées)"),
                        ],
                        default="individuelle",
                        max_length=20,
                    ),
                ),
                ("coefficient_groupe", models.FloatField(default=0.5)),
                ("coefficient_individuel", models.FloatField(default=0.5)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de soutenance",
                "verbose_name_plural": "Sessions de soutenance",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PassageEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_groupe",
                    models.CharField(
                        choices=[
                            ("monome", "Monôme (1 étudiant)"),
                            ("binome", "Binôme (2 étudiants)"),
                            ("groupe", "Groupe (3+ étudiants)"),
                        ],
                        default="monome",
                        max_length=10,
                    ),
                ),
                ("ordre_passage", models.PositiveIntegerField(default=1)),
                ("heure_prevue", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours — présentation"),
                            ("questions", "Session questions"),
                            ("termine", "Terminé — notation en cours"),
                            ("note", "Noté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "fichier_pptx",
                    models.FileField(blank=True, null=True, upload_to="pptx/"),
                ),
                (
                    "fichier_rapport",
                    models.FileField(blank=True, null=True, upload_to="rapports/"),
                ),
                (
                    "enregistrement_video",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                ("transcription", models.TextField(blank=True)),
                ("donnees_posture", models.JSONField(blank=True, default=dict)),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "etudiants",
                    models.ManyToManyField(
                        related_name="passages", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="sessions_app.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passage étudiant",
                "verbose_name_plural": "Passages étudiants",
                "ordering": ["session", "ordre_passage"],
            },
        ),
        migrations.CreateModel(
            name="CritereNotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("coefficient", models.FloatField(default=1.0)),
                (
                    "est_personnalise",
                    models.BooleanField(
                        default=False,
                        help_text="True si entré librement par le prof (sinon, critère prédéfini)",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteres",
                        to="sessions_app.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critère de notation",
                "verbose_name_plural": "Critères de notation",
                "ordering": ["ordre", "id"],
            },
        ),
    ]
