# Generated by Django 4.2.16 — patched for existing rows
import secrets
import string

from django.conf import settings
from django.db import migrations, models


def _generer_code():
    return ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(8))


def populate_codes(apps, schema_editor):
    """Attribue un code unique à chaque session existante."""
    Session = apps.get_model('sessions_app', 'Session')
    used = set()
    for session in Session.objects.all():
        if not session.code_acces:
            code = _generer_code()
            while code in used:
                code = _generer_code()
            session.code_acces = code
            session.save(update_fields=['code_acces'])
            used.add(code)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sessions_app", "0001_initial"),
    ]

    operations = [
        # 1. Ajouter le champ sans contrainte UNIQUE d'abord
        migrations.AddField(
            model_name="session",
            name="code_acces",
            field=models.CharField(
                blank=True,
                default='',
                help_text="Partagez ce code aux étudiants pour qu'ils rejoignent la session",
                max_length=10,
                verbose_name="Code d'accès",
            ),
        ),
        # 2. Remplir les codes pour les lignes existantes
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
        # 3. Ajouter la contrainte UNIQUE maintenant que toutes les lignes ont un code
        migrations.AlterField(
            model_name="session",
            name="code_acces",
            field=models.CharField(
                blank=True,
                help_text="Partagez ce code aux étudiants pour qu'ils rejoignent la session",
                max_length=10,
                unique=True,
                verbose_name="Code d'accès",
            ),
        ),
        # 4. Champ inscrits (M2M, pas de problème)
        migrations.AddField(
            model_name="session",
            name="inscrits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Étudiants ayant rejoint la session (via code ou ajout manuel)",
                related_name="sessions_inscrites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Étudiants inscrits",
            ),
        ),
    ]
