# Generated by Django 4.2.16 on 2026-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0004_dual_personnalite"),
    ]

    operations = [
        migrations.AddField(
            model_name="passageetudiant",
            name="transcriptions_par_etudiant",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"<user_id>": "<texte>"} — renseigné si chaque étudiant se connecte depuis son propre appareil.',
                verbose_name="Transcriptions par étudiant",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
