# Generated by Django 4.2.16 on 2026-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0006_add_syntheses_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="passageetudiant",
            name="analyses_extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"demo_video": {...}, "github": {...}}',
                verbose_name="Analyses supplémentaires (vidéo + GitHub)",
            ),
        ),
        migrations.AddField(
            model_name="passageetudiant",
            name="fichier_demo_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="demos/",
                verbose_name="Vidéo de démonstration",
            ),
        ),
        migrations.AddField(
            model_name="passageetudiant",
            name="url_depot_github",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="URL dépôt GitHub"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="coefficient_demo_video",
            field=models.FloatField(
                default=1.0,
                help_text="Poids de la note démo dans la note finale",
                verbose_name="Coefficient démo vidéo",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="coefficient_github",
            field=models.FloatField(
                default=1.0,
                help_text="Poids de la note GitHub dans la note finale",
                verbose_name="Coefficient GitHub",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="criteres_github",
            field=models.TextField(
                blank=True,
                help_text="Ex : Propreté du code, README complet, tests unitaires, historique commits",
                verbose_name="Critères d'évaluation GitHub",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="demo_video_instructions",
            field=models.TextField(
                blank=True,
                help_text="Ex : Montrez votre robot éviter un obstacle sur 30 secondes",
                verbose_name="Consignes pour la démo vidéo",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="demo_video_requise",
            field=models.BooleanField(
                default=False,
                help_text="L'étudiant devra déposer une vidéo de démonstration (app, robot, interface…)",
                verbose_name="Démo vidéo requise",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="depot_github_requis",
            field=models.BooleanField(
                default=False,
                help_text="L'étudiant devra fournir l'URL de son dépôt GitHub public",
                verbose_name="Dépôt GitHub requis",
            ),
        ),
        migrations.AlterField(
            model_name="passageetudiant",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours — présentation"),
                    ("questions", "Questions"),
                    ("termine", "Terminé — notation en cours"),
                    ("note", "Noté"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
