# Generated by Django 4.2.16 on 2026-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0007_add_demo_video_and_github_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="passageetudiant",
            name="rappel_envoye",
            field=models.BooleanField(
                default=False,
                help_text="Vrai si le rappel email pré-passage a déjà été envoyé.",
                verbose_name="Rappel 10 min envoyé",
            ),
        ),
    ]
